repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "v4.5.0"
    hooks:
      - id: "trailing-whitespace"
      - id: "end-of-file-fixer"
      - id: "check-yaml"
        args:
          - "--unsafe"
      - id: "check-added-large-files"
        args:
          - "--maxkb=6000"
  - repo: "https://github.com/astral-sh/ruff-pre-commit"
    rev: "v0.2.1"
    hooks:
      - id: "ruff"
        types_or:
          - "python"
        args:
          - "--fix"
      - id: "ruff-format"
        types_or:
          - "python"
  - repo: "https://github.com/pre-commit/mirrors-clang-format"
    rev: "v18.1.8"
    hooks:
      - id: "clang-format"
        types_or:
          - "c++"
          - "c"
